// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFlmvPmIZF6kkxktimWZ0PA9wbFwExfRY',
    appId: '1:119354287396:web:09587ab22d24a94ef0ffb1',
    messagingSenderId: '119354287396',
    projectId: 'bemyeyes-2c3d4',
    authDomain: 'bemyeyes-2c3d4.firebaseapp.com',
    storageBucket: 'bemyeyes-2c3d4.firebasestorage.app',
    measurementId: 'G-B7RFFVTSMG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrb1uPZw48lJGbyRPN3fLZCQ3COqqK04c',
    appId: '1:119354287396:android:d4827ef0dea76228f0ffb1',
    messagingSenderId: '119354287396',
    projectId: 'bemyeyes-2c3d4',
    storageBucket: 'bemyeyes-2c3d4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcLg66zpmzLyadXPp2t8_i53qRLIecIHI',
    appId: '1:119354287396:ios:9e6cb1680a27b3b4f0ffb1',
    messagingSenderId: '119354287396',
    projectId: 'bemyeyes-2c3d4',
    storageBucket: 'bemyeyes-2c3d4.firebasestorage.app',
    iosBundleId: 'com.example.eyeconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcLg66zpmzLyadXPp2t8_i53qRLIecIHI',
    appId: '1:119354287396:ios:9e6cb1680a27b3b4f0ffb1',
    messagingSenderId: '119354287396',
    projectId: 'bemyeyes-2c3d4',
    storageBucket: 'bemyeyes-2c3d4.firebasestorage.app',
    iosBundleId: 'com.example.eyeconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFlmvPmIZF6kkxktimWZ0PA9wbFwExfRY',
    appId: '1:119354287396:web:c2d87562ce474316f0ffb1',
    messagingSenderId: '119354287396',
    projectId: 'bemyeyes-2c3d4',
    authDomain: 'bemyeyes-2c3d4.firebaseapp.com',
    storageBucket: 'bemyeyes-2c3d4.firebasestorage.app',
    measurementId: 'G-WPQ2XLFS7N',
  );
}
